### ISSUE TITLE
IntelliJ UI Hangs

### ISSUE THREAD

**Issue by jeetgajjar** [vcu-swim-lab/stack-intheflow#135]
https://youtrack.jetbrains.com/issue/IDEA-180506 
SIF has the IDEA UI hanging at random times during development.
I followed the advice and have removed SIF from my plugins and IDEA works just fine now.

See the stack trace:
```
"AWT-EventQueue-0 2017.2.5#IC-172.4343.14 IDEA, eap:false, os:Mac OS X 10.12.6, java-version:JetBrains s.r.o 1.8.0_152-release-915-b12" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE
 (in native)
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:171)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
    at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
    at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
    at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:394)
    at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
    at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
    at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.put(JerseyInvocation.java:326)
    at io.github.vcuswimlab.stackintheflow.controller.LogServer.LogToServer(LogServer.java:53)
    at io.github.vcuswimlab.stackintheflow.controller.Logging.info(Logging.java:42)
    at io.github.vcuswimlab.stackintheflow.model.difficulty.DifficultyModel.lambda$new$2(DifficultyModel.java:137)
    at io.github.vcuswimlab.stackintheflow.model.difficulty.DifficultyModel$$Lambda$611/651117243.doEdit(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:443)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:404)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:393)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:381)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:374)
    at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:45)
    at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:231)
    at com.sun.proxy.$Proxy97.doEdit(Unknown Source)
    at io.github.vcuswimlab.stackintheflow.controller.component.document.DocumentListenerComponent$1.lambda$fileOpened$0(DocumentListenerComponent.java:94)
    at io.github.vcuswimlab.stackintheflow.controller.component.document.DocumentListenerComponent$1$$Lambda$803/1876784289.visibleAreaChanged(Unknown Source)
    at com.intellij.openapi.editor.impl.ScrollingModelImpl$2.stateChanged(ScrollingModelImpl.java:86)
    at javax.swing.JViewport.fireStateChanged(JViewport.java:1369)
    at javax.swing.JViewport.reshape(JViewport.java:839)
    at java.awt.Component.setBounds(Component.java:2269)
    at java.awt.Component.setBounds(Component.java:2413)
    at com.intellij.ui.components.JBScrollPane$Layout.layoutContainer(JBScrollPane.java:511)
    at java.awt.Container.layout(Container.java:1511)
    at com.intellij.openapi.editor.impl.EditorImpl$MyScrollPane.layout(EditorImpl.java:4503)
    at java.awt.Container.doLayout(Container.java:1500)
    at java.awt.Container.validateTree(Container.java:1696)
    at java.awt.Container.validateTree(Container.java:1705)
    at java.awt.Container.validateTree(Container.java:1705) 
```

Let me know if I can provide more details.

**Comment by Zerthick** [comment]
Looks like communication to the logging server is being done on the main thread, oops.
