### ISSUE TITLE
Your platform does not support JavaFX.

### ISSUE THREAD

**Issue by gilshallem** [vcu-swim-lab/stack-intheflow#144]
I get the error even though i did set the system var.

![image](https://user-images.githubusercontent.com/8035623/46861253-791b6c00-ce3c-11e8-9312-d6cbfe19633f.png)
![image](https://user-images.githubusercontent.com/8035623/46861273-833d6a80-ce3c-11e8-9089-9dcddf1536e9.png)

**Comment by damevski** [comment]
@gilshallem There seems to be an issue with recent versions of AndroidStudio where STUDIO_JDK just does not work as advertised. 

https://issuetracker.google.com/issues/80362789

We are currently working on a more permanent solution to this problem, which stems from Android Studio not packaging JavaFX by default, while IntelliJ does. 

Thanks for reporting the issue!

**Comment by gilshallem** [comment]
Cool, thanks, maybe you can add a way to determine the path to JDK in the plugin instead of using the visual studio path?

**Comment by gilshallem** [comment]
I manage to solve it via this instructions: https://intellij-support.jetbrains.com/hc/en-us/articles/206544879

**Comment by gilshallem** [comment]
correction: after I changed the studio jdk (ctrl+shif+a->switch JDK) to the latest one i get this error

> ReferenceError: Can't find variable: $
netscape.javascript.JSException: ReferenceError: Can't find variable: $
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:156)
	at com.sun.webkit.dom.JSObject.callImpl(Native Method)
	at com.sun.webkit.dom.JSObject.call(JSObject.java:125)
	at io.github.vcuswimlab.stackintheflow.view.SearchToolWindowGUI.lambda$null$1(SearchToolWindowGUI.java:120)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1287)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1401)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1280)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1267)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2518)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2362)
	at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
	at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:871)
	at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$105(URLLoader.java:862)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)


The plugin now display the UI but nothing works

**Comment by damevski** [comment]
@gilshallem we will try to address this issue over the winter break (Dec - Jan); we just don't have the time at the moment. if you have ideas on how to fix it in the shorter run, we would be very happy to hear your thoughts or even integrate your solution.
